version: 2
updates:
  - package-ecosystem: cargo
    directory: /caby-service
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      cargo-non-major:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /caby-web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-non-major:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-non-major:
        update-types: [minor, patch]

  - package-ecosystem: docker
    directories:
      - /caby-service/ci
      - /caby-web/ci
    schedule:
      interval: weekly
