stages:
  - release

.kaniko-release:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR/$SERVICE
      --dockerfile $CI_PROJECT_DIR/$SERVICE/ci/Dockerfile
      --destination $IMAGE:$CI_COMMIT_SHA
      --destination $IMAGE:latest
      --cache=true
      --cache-repo=$CACHE_IMAGE

release-api:
  extends: .kaniko-release
  variables:
    SERVICE: caby-service
    IMAGE: $CI_REGISTRY_IMAGE/caby-service
    CACHE_IMAGE: $CI_REGISTRY_IMAGE/caby-service/cache
  rules:
    - changes:
      - caby-service/**/*

release-web:
  extends: .kaniko-release
  variables:
    SERVICE: caby-web
    IMAGE: $CI_REGISTRY_IMAGE/caby-web
    CACHE_IMAGE: $CI_REGISTRY_IMAGE/caby-web/cache
  rules:
    - changes:
      - caby-web/**/*

