# A list of spaces or compartments
spaces:
  - name: home
    display: "🏠 Home"
  - name: media
    display: "🎞️ Media"

users:
  - name: caby_user
    # a token for first-time login — generate one with `openssl rand -hex 32`
    activation_token: REPLACE_ME
    spaces:
      - name: home
        permissions: "*"
      - name: media
        permissions: "*"
