{{- if and (not .Values.config.existingSecret) .Values.config.inline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-config" (include "caby.fullname" .) }}
  labels:
    {{- include "caby.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "caby.configSecretKey" . }}: |
{{ .Values.config.inline | indent 4 }}
{{- end }}
