{{- if .Values.backend.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-env" (include "caby.fullname" .) }}
  labels:
    {{- include "caby.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.backend.secretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
